### ISSUE TITLE
Error when uising /pleasewelcome help

### ISSUE THREAD

**Issue by duhadventure** [Katrix-/PleaseWelcome#2]
Sponge:7.1.3-RC3498
PW: 7-0-0-1.1.0
`[15:06:05] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'pleasewelcome help' for source EntityPlayerMP['duhadventure'/151, l='world', x=-367.19, y=145.62, z=668.39]: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V
        at io.github.katrix.katlib.KatPlugin$$anon$1.sendPagination(KatPlugin.scala:67) ~[KatPlugin$$anon$1.class:2.4.0]
        at io.github.katrix.katlib.command.CmdHelp.$anonfun$execute$1(CmdHelp.scala:76) ~[CmdHelp.class:2.4.0]
        at io.github.katrix.katlib.i18n.Localized$.apply(Localized.scala:9) ~[Localized$.class:2.4.0]
        at io.github.katrix.katlib.command.CmdHelp.execute(CmdHelp.scala:62) ~[CmdHelp.class:2.4.0]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.3-RC3498]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.3-RC3498]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.3-RC3498]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.3-RC3498]
        at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:960) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:939) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.3-RC3498]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.3-RC3498]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

**Comment by Katrix** [comment]
Hi, can you put the error in a file here, or on hastebin, or anywhere really anywhere that doesn't wrap it in that way? Would be much easier to read the error that way.

**Comment by Katrix** [comment]
Just as another question, which version of KatLib are you using?

**Comment by duhadventure** [comment]
> Just as another question, which version of KatLib are you using?

AKatLib-7.0.0-assembly-2.4.0
